### ISSUE TITLE
Deprecation warnings from ember-modifier [use-modify & no-args-property]

### ISSUE THREAD

**Issue by jacobq** [PrecisionNutrition/ember-resize-kitchen-sink#12]
Deprecation warnings encountered when using this addon:

* "The `didInstall`, `didReceiveArguments`, and `didUpdateArguments` hooks are deprecated. Use the new `modify` hook instead. [deprecation id: ember-modifier.use-modify]"
* "using `this.args` is deprecated. Access positional and named arguments directly in the `modify` hook instead. [deprecation id: ember-modifier.no-args-property]"

Appears to be coming from here: 
https://github.com/PrecisionNutrition/ember-resize-kitchen-sink/blob/1e1797e98246e7903e6c58529344e23f9ef6ade0/packages/ember-on-resize-modifier/addon/modifiers/on-resize.js#L9-L22

See also:

* https://github.com/ember-modifier/ember-modifier/commit/5dafa2801d2bccb4a5a074535ab7640a69265512
* https://github.com/ember-modifier/ember-modifier/pull/217

**Comment by bertdeblock** [comment]
#11 should resolve this.
