### ISSUE TITLE
Upgrade ember-modifier to 3.x

### ISSUE THREAD

**Issue by mayatron** [PrecisionNutrition/ember-resize-kitchen-sink#4]
Upgrade `ember-modifier` to current version: https://github.com/ember-modifier/ember-modifier/releases

Or optionally at least allow the newer version: `"ember-modifier": "^2.1.2 || ^3.0.0"`

**Comment by jherdman** [comment]
Are you amenable to opening a pull request that does this work?

**Comment by jherdman** [comment]
Resolved by #5
